services:
  redis:
    env_file:
      - .env
    build:
      context: ./images
      dockerfile: redis.Dockerfile
    container_name: sens-kv
    volumes:
      - sens-kv:/data
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    restart: always

volumes:
  sens-kv:
    driver: local